# Site settings
title: MissyBur - A blog about my projects
email: missybur@gmail.com
description: A blog about my projects.
url: "http://MissyBur.me" # the base hostname & protocol for your site
twitter_username: missybur
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Missy Bur
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





